.TH rklogger 1 2015-01-30 "rklogger 1.1"
.SH NAME
rklogger \- Command line tool for reading solar inverter parameters via the ComLynx protocol
.SH SYNOPSIS
.B rklogger 
.RB [\| \-D
.IR device \|]
.I network 
.I node
.LP
.B rklogger 
.RB [\| \-D
.IR device \|]
.I network 
.I node 
.I param_idx 
.I param_subidx 
.I param_modulidx
.LP
.B rklogger
.RB [\| \-D
.IR device \|]
.B \-s
.SH DESCRIPTION
rklogger is a command line tool to read parameters from a ComLynx enabled solar
inverter. It requires the inverter to be accessible via a serial line
interface, e.g., a USB to EIA\-485 converter on
.IR /dev/ttyUSB0 .
.SH OPTIONS
.SS General options
.TP
.BI \-D \ device
Use 
.I device
instead of the default device 
.IR /dev/ttyUSB0 .
.SS Inverter address 
.TP
.I network
The id of the network
.TP
.I node
The id of the node
.SS Requesting a parameter.
.TP
.I param_idx
The index for the parameter that is requested.
.TP
.I param_subidx
The subindex for the parameter that is requested.
.TP
.I param_modulidx
The modul index for the parameter that is requested.
.SS Scanning the network.
.TP
.B \-s
Initiate a network scan. 
.SH BUGS
The current release cannot handle EIA\-485 interfaces mirror characters that
are send back to the receiver.
.SH AUTHOR
Written by Thomas Petig.
.SH COPYRIGHT
Copyright (C) 2015 Thomas Petig
License GPLv3+
