name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install libboost-all-dev
    - name: Run a multi-line script
      run: |
        mkdir build
        cd build
        cmake ..
        make VERBOSE=1
